# Generated by Django 4.2.6 on 2023-10-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='carro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='placa',
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Vermelho', 'Vermelho')], max_length=255),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carro_app.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelos',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carro_app.modelo'),
        ),
    ]
