# Generated by Django 4.2.6 on 2023-10-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_app', '0002_marca_remove_carro_ano_remove_carro_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagems',
                'db_table': 'imagens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carro_app.carro')),
                ('imagens', models.ManyToManyField(blank=True, to='Carro_app.imagem', verbose_name='imagens')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'albuns',
                'managed': True,
            },
        ),
    ]
