# Generated by Django 4.2.6 on 2023-10-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_app', '0004_remove_album_carro_carro_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='fotos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carro_app.album'),
        ),
    ]
