# Generated by Django 4.2.6 on 2023-10-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro_app', '0006_alter_imagem_options_remove_album_imagens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='imagens',
            field=models.ManyToManyField(blank=True, null=True, related_name='albuns', to='Carro_app.imagem'),
        ),
    ]
